### ISSUE TITLE
"Software Failure" after installing OMV 6 extras

### ISSUE THREAD

**Issue by angelpradomx** [OpenMediaVault-Plugin-Developers/packages#10]
I'm not able to install OMV-extras for OMV6

After installation always by clicking in the webgui to the omv-extras, there is coming a error message. "Software Failure".

The issue is resolved by using the "reset the ui to defaults" menu option, but for as a first time user I think many people would be facing this isue with recent setups.

**Comment by ryecoaaron** [comment]
This actually belongs - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues

But there is nothing the plugin can do to help this since it has to be installed from the command line and is a client side browser cache that causes this issue.  That is why the # 1 problem is listed in the "Solution to Common Problems" thread on the forum - https://forum.openmediavault.org/index.php?thread/21269-solutions-to-common-problems/.  ctrl-shift-R will fix the problem.

**Comment by ryecoaaron** [comment]
How did you install it by the way?  I guess I could add output to the install script to tell you to ctrl-shift-R.
