### ISSUE TITLE
Replace MD5 hash with SHA256 or SHA512 / add GPG verification

### ISSUE THREAD

**Issue by ovz93br43v7** [OpenMediaVault-Plugin-Developers/packages#2]
As far as I know MD5 hash is not anymore state of the art. Can you replace this with SHA256 or SHA512?
Can you also add a GPG verification for download and/or hash?

**Comment by ryecoaaron** [comment]
I just used md5 because it would tell you if downloaded correctly.  I wasn't trying to prevent someone spoofing the hash and injecting content.  I guess I can add the sha sums.

Adding gpg verification is pretty close to putting it in a repo.  And while the package is in a repo, the whole point of the package is to add the repo.  If you want to manually add the repo and key from bintray (https://bintray.com/openmediavault-plugin-developers/usul/openmediavault-omvextrasorg), the package is signed there.

**Comment by ryecoaaron** [comment]
sha256 and sha512 added.
