### ISSUE TITLE
openmediavault-syncthing is not update

### ISSUE THREAD

**Issue by vitofasano** [OpenMediaVault-Plugin-Developers/packages#4]
openmediavault-syncthing is not at last version (v1.18.0) but it is at v1.15.1

**Comment by ryecoaaron** [comment]
The syncthing plugin was EOL'd with OMV 4.x (which is also EOL'd).  But the syncthing package itself never came from the plugin or omv-extras repo.  It came from the syncthing repo that was added by omv-extras.  Maybe that repo has changed?  Not sure but since everything OMV 4.x is EOL',d it will require a manual change.  I recommend upgrading to OMV 5.x and using syncthing in docker.
